### ISSUE TITLE
Remove me from fossmagic mailing list admin

### ISSUE THREAD

**Issue by msoucy** [FOSSRIT/tasks#104]
I don't actually have my password for it, so can't do it myself. Every day I get an email about people waiting for approval that I can't do anything about

**Comment by jwflory** [comment]
You are not an owner or moderator to the `fossrit [at] lists.fedoraproject [dot] org` mailing list and this is the list I have access to. I assume you are referring to a mailing list managed by either @itprofjacobs, @ritjoe, or someone else on @FOSSRIT/foss-magic-faculty-and-staff.

**Comment by msoucy** [comment]
Yeah, it's one from Rit directly, not fedora. It was made back in my final year I believe

**Comment by ritjoe** [comment]
This one, I think:

https://lists.rit.edu/mailman/listinfo.mmcgi/fossmagic

Just a guess, but we'll probably have to contact IT and SJ to coordinate an admin password reset and perhaps add/change administrators.

**Comment by ritjoe** [comment]
On Sun, Nov 10, 2019 at 03:56:54AM -0800, Joe wrote:
> 
> This one, I think:
> 
> https://lists.rit.edu/mailman/listinfo.mmcgi/fossmagic
> 
> Just a guess, but we'll probably have to contact IT and SJ to coordinate an
> admin password reset and perhaps add/change administrators.
> 
>

After our Wednesday meeting, I stopped by the ITS desk (in Booth I think?) and asked they open a ticket directed at SJ (@itprofjacobs) but Cc:'ing me for assistance.

I thought they were going to do a password reset for him. 

I have not finished combing through my spam boxes to make sure one hasn't gotten filtered out, but I do not yet see an email from them regarding this.

So, we're trying, but we're not there yet I don't think. Sorry.

**Comment by ritjoe** [comment]
Done.

For posterity's sake, unbeknownst to me, they emailed him several times. Finally, they copied me in on one of the messages (possible there are Cc:'s that got caught as spam but we'll see next time I'm spelunking down in the spam boxes). He and I talked about it, he did the necessary, they did the necessary, I got access, I logged in and removed whatever address it was (I suppose I should have looked to see which it was). 

It occurs to me that somewhere in the headers of the email you got @msoucy there would be an indication as to what address it was sending to. No big deal now but I mention it since it does now occur to me.

Closing.

**Comment by jwflory** [comment]
@ritjoe Thanks for taking care of this one, I wouldn't have known how to handle this!

@msoucy Let us know if you continue to receive any emails from this list.

**Comment by msoucy** [comment]
Will do, thank you! Sorry about the hassle.

**Comment by itprofjacobs** [comment]
Sorry it took so long to figure it out
