### ISSUE TITLE
Issue template for bridging rooms

### ISSUE THREAD

**Issue by ct-martin** [FOSSRIT/tasks#119]
# Summary

Simplified issue template reflecting the complexity of adding new bridges for IRC<->Slack/TG rooms.

# Background

The infrastructure already exists for bridging between TG<->IRC & Slack<->IRC for FOSSRIT rooms. We already have 18 bridges and adding more is not a complicated affair in the way provisioning a new server is. A four-section issue template is overkill for asking to bridge a chat room.

# Details

Proposing something to the effect of the following:

> # This is requesting a bridge between:
> * [ ] IRC & Telegram
> * [ ] IRC & RITlug Slack
>
> # Room names (for all applicable)
> * Freenode: `#(room name here)`
> * Telegram: `(room name/link here)`
> * RITlug Slack: `#(room name here)`

If you feel it's merited, I don't have issue with a short question asking the relevance of the channel in a sentence.

# Outcome

Create a new issue template for bridging rooms that is concise and easy to fill out

**Comment by jwflory** [comment]
Thanks for the suggestion @ct-martin, I agree with you. A template would make this type of request more straightforward.

I moved this issue here from FOSSRIT/infrastructure because I wanted to ask @FOSSRIT/tech-team a question. Given the focus of this repo as a public task tracker for the wider community, and that FOSSRIT/infrastructure is mostly managed by Tech Team members, does it make sense to add the template to this repo or the Infrastructure repo?

My first thought is to add it here. This way, the type of request is visible along with the other things people can ask for here. It would become the responsibility of @FOSSRIT/tech-team members to watch this repo for specific types of tasks (I could also automatically assign bridge requests to @FOSSRIT/ansible-maintainers for instance). In this approach, Tech Team members could choose to migrate an issue to the FOSSRIT/infrastructure repo or simply close the issue out here when it's done.

Before I made this decision, I wanted to throw it out there if anyone had a preference on this, given I'm leaving RIT full-time at the end of March.
