### ISSUE TITLE
Install Discourse for better discussion among RIT FOSS folk

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#58]
# Summary

Install [Discourse](https://www.discourse.org/) on provisioned infrastructure to host community discussions and better engage with interested people

# Background

We wanted to consider a better platform for hosting discussion and having wider discourse between different segmented pieces of the FOSS community at RIT. This offers an alternate to the existing mailing list in an intuitive interface. Mailing list-style functionality is available for those who prefer to remain up-to-date by email. 

# Details

This ticket is blocked by #56. Once unblocked, the following needs to be done:

1. Install Discourse on machine (with as much automation as possible)
2. Configure to preference
3. (_not yet confirmed_) Follow-up discussion with Amit Ray on inclusion to courses
4. Make public announcement and begin circulating its presence (on mailing lists and on website, #57)

# Outcome

Better platform to encourage discussion and engagement between FOSS students, alums, faculty, and staff, as well as provide a MyCourses alternate for some FOSS courses

**Comment by ct-martin** [comment]
As a note, currently the _people_ are on the mailing list and if this is going to replace the mailing list then there should be at least a temporary bridge since the _human issue_ rather than the _technical issue_ is probably going to be the most difficult & significant part of this.

Also, if the goal is an intuitive interface alternative to the mailing list then Hyperkitty may be worth thinking about, however, that shouldn't detract from the original point.

**Comment by ritjoe** [comment]
On Sat, Oct 13, 2018 at 02:09:02PM -0700, Christian Martin wrote:

> Also, if the goal is an intuitive interface alternative to the mailing list
> then Hyperkitty may be worth thinking about, however, that shouldn't detract
> from the original point.

To some points of information:

There are two mailing lists associated with FOSS@RIT. 

The oldest is the floss-seminar list that was used for the original honors seminar class and was revived by me for HFOSS use. It is hosted by RIT on a Mailman 2 instance. Its archive is subscriber-only, and generally only students, alumni, or instructors are ever subscribed.

https://lists.rit.edu/mailman/listinfo.mmcgi/floss-seminar

 Its scope, then, is much more focussed and its reach more limited.


The newer one is the 'fossrit' list. It is hosted by the Fedora Project. It also was created in earlier days of the academic side of the FOSS@RIT efforts, and then later revived. However, its archive is public and its membership meant to be significantly more open, inclusive, and outward facing. 

It does, in fact, use Mailman 3 and a HyperKitty interface:

https://lists.fedoraproject.org/archives/list/fossrit@lists.fedorahosted.org/

**Comment by ct-martin** [comment]
@ritjoe my understanding was that this would replace the FOSSRIT (Fedora hosted) list, although I guess it might end up being used for FLOSS Seminar. It should be worth noting that none of this is documented in the issue, but @jwflory asked me to drop that in here from an in-person discussion (re: RITlug forwarding to an outside list) and I am not fully aware what the discussion around this is

**Comment by jwflory** [comment]
Aiming to revisit this in December.

**Comment by jwflory** [comment]
Some initial notes:

* See upstream's [cloud install guide](https://github.com/discourse/discourse/blob/master/docs/INSTALL-cloud.md)
* Need to find a domain to run this site on. I was thinking `fossrit.community` but I'd like to purchase a domain the right way this time and hopefully have it managed / billed directly to MAGIC instead of by a student

**Comment by jwflory** [comment]
The Discourse website is now online at [fossrit.community](https://fossrit.community/). I'm going to close this ticket as complete. :clapper: 

Once I have a chance to catch up with @itprofjacobs, we'll figure out a strategy to promote the new site and grow a community on Discourse.

**Comment by ct-martin** [comment]
@jwflory depending on how the various FOSSRIT sites end up being set up, it
may make more sense to put the Discourse on a subdomain. This is something
that will need to be discussed with SJ after the part-time hiring is done
though.

--
Christian Martin (Phone)

**Comment by jwflory** [comment]
@ct-martin Could you clarify what you mean by other FOSSRIT sites?

**Comment by ct-martin** [comment]
@jwflory FOSS.rit.edu, the old foss.rit.edu, fossrit.github.io,
HFOSS.rocfoss.org, and there might be another one somewhere iirc but I
don't remember where offhand. Will this all end up under FOSS.rit.edu, or
will we want any of it under fossrit.community? Do we want to have
FOSSRIT.community CNAME (have the DNS point) to what is now
fossrit.github.io and then worry about mirroring/CD-ing it to FOSS.rit.edu
later (due to the quirks of running servers inside RIT that interact with
servers outside RIT)?

Main point from a DNS organization/planning standpoint, will we (reasonably
likely) want a non-forum site at the top level in the near/mid-term future,
or will this domain just be the forum for the foreseeable future? It's
cleaner semantics to do `www./example.com` and `forum.example.com` than
`www./example.com` as the forum and `info.example.com` or `about.example.com`
for the site.

**Comment by jwflory** [comment]
The `fossrit.community` domain is only intended for use with Discourse.
