### ISSUE TITLE
Create and hang posters for upcoming FOSS courses

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#72]
# Summary

Update the old FOSS course posters, get them spread out around campus before shopping carts open

# Background

Need to make sure we have accurate count of what courses are running.

# Details

@itprofjacobs to work with design student / Brenda at MAGIC to update poster design. @jwflory to help with poster distribution and getting them hung around campus.

# Outcome

Better visibility about what FOSS courses will run next semester

**Comment by ritjoe** [comment]
On Wed, Oct 17, 2018 at 10:11:34AM -0700, Justin W. Flory wrote:
> Summary
> 
> Update the old FOSS course posters, get them spread out around campus before
> shopping carts open

As per

https://www.rit.edu/infocenter/sites/rit.edu.infocenter/files/images/2018-19%20Enrollment%20Dates%2010-3-18.pdf

"Shopping Carts for Spring Open October 29, 2018"

**Comment by ritjoe** [comment]
On Wed, Oct 17, 2018 at 10:11:34AM -0700, Justin W. Flory wrote:
> Background
> 
> Need to make sure we have accurate count of what courses are running.

Not so much a count as a list?

https://gitlab.com/deejoe/rit-year-of-foss

was what I transcribed from Dan's poster last spring of the courses that were meant to have run this year. It should provide a reasonable base for enumerating what will run in this spring so one need not start from scratch. It'll need checking and will probably need additions and deletions. 

If there's a format you'd find more convenient please let me know and I'll see if I can drive pandoc to do the modifications or otherwise see if I can effect the transformation for you so you don't have to key everything in again.

**Comment by jwflory** [comment]
@itprofjacobs Did we end up printing posters? Or do we want to skip this since we're late on enrollment?

**Comment by ritjoe** [comment]
On Tue, Nov 13, 2018 at 08:42:17AM -0800, Justin W. Flory wrote:
> @itprofjacobs Did we end up printing posters? Or do we want to skip this since
> we're late on enrollment?


A few observations:

None of our courses are yet full.

We can continue to accept enrollees.

Generally, we need to continue to accept enrollees for HFOSS.

As best I can tell, this is true specifically for this semester too.

Posters probably build general awareness amongst returning students, and we can take advantage of that in subsequent years.

**Comment by jwflory** [comment]
> Posters probably build general awareness amongst returning students, and we can take advantage of that in subsequent years.

+1. Briefly checked in with @itprofjacobs and decided we missed the boat on this one this year.

Closing. :clapper:
