### ISSUE TITLE
UNICEF Create Rubric for FOSS Strategy

### ISSUE THREAD

**Issue by whenbellstoll** [FOSSRIT/tasks#86]
### >>> [**Working draft of rubric**](https://docs.google.com/spreadsheets/d/16IWa_TFB8wx2_R_Fk9-Y80b5n1BF32SvwwcnrsB3waA/edit?usp=sharing) <<<

# Summary

Working off of the success criteria, a need for a method of grading tasks is needed.

# Background

Utilizing the Flory Plan, Callaway Coefficient of Failure, and Karl Fogel's Producing Open Source Software we plan to make a rubric that can guide teams in the implementation of Open Source in their individual projects.

# Details

- Decide on a Grading Scale.
- How we will compartmentalize the Flory Plan into rubrics.
- Turn the concepts from the sources into actionable tasks for the teams.
- Create general timeline for each rubric.

# Outcome

We can evaluate each team.

**Comment by Nolski** [comment]
Curious as to why we're using a rubric for evaluation vs success metrics? Success for running an open source project can be really relative here, especially when the teams are so new and inexperienced, I'm worried we might just be handing out F's to everyone.

**Comment by jwflory** [comment]
@Nolski In the [rubric topics overview doc](https://docs.google.com/document/d/1A6K7zKLlEdt5HgP351weECYt2ZYjmlmq08ZH2zScAVA/edit?usp=sharing), we changed to a green-yellow-red light method of evaluating. Green for exceptional, yellow for good start but needs work, red for absent / incomplete. Not everything will be green and we should be clear we don't expect that, but the idea is this also gives a framework for the cohorts to self-evaluate themselves on. Ideally, we will share this with UNICEF as well as with the cohorts and empower them to make this a useful tool for themselves.

**Comment by whenbellstoll** [comment]
Major progress on making the rubrics today, I worked out the requirements for each topic of the Success Criteria, those with permission can view my drafts [here.](https://drive.google.com/drive/folders/1FXzoLDD1F--Efu3FO0BPthC-eK3CFSLS) Really excited to start finishing these and handing them off to the team later this week.

**Comment by whenbellstoll** [comment]
Finished the first drafts for all of the rubrics today, they can be found [here.](https://drive.google.com/drive/folders/1FXzoLDD1F--Efu3FO0BPthC-eK3CFSLS) Over the next couple of days @Nolski @itprofjacobs  and @jwflory  could view those documents, add suggestions, and correct errors. I'll be reviewing them myself, but I also want to move on to writing the wiki and get the [High Level Overview](https://github.com/FOSSRIT/tasks/issues/96) done.

**Comment by Nolski** [comment]
Hi all,

Great job on this rubric so far @whenbellstoll! I have a couple of comments and questions about the format of this document.

It seems like there's quite a large amount of documents here for just one rubric. I fear this might end up looking like a really heavy lift for the companies wanting to incorporate and measure FOSS success. 

Some sections (such as bug tracker) can be entirely dismissed into the green section if they're using something such as github. I wonder if there's a way we can make evaluating these sections a bit easier by having some comment presets or something like that.

With that being said, I have a couple of suggestions:

- Can we move these separate documents into one separating each section with a header? Should be a simple copy and paste.
- Once that's completed, we can begin evaluating if there's areas that can be stripped out.
- Since these are excel sheets (or similar) I think we can use functions where you have a select box that will autofill/grade based on your input. For instance, next to the issue tracker, if you select github/gitlab, it will auto-grade you because we know what github/gitlab provides.

What do y'all think?

**Comment by itprofjacobs** [comment]
Suggestions make sense to me

**Comment by whenbellstoll** [comment]
Thanks @Nolski I can start on those suggestions right away.

**Comment by whenbellstoll** [comment]
Progress on the rubrics, I put all of them into one document, separated by headers, as @Nolski  suggested, you can fin it [here.](https://docs.google.com/spreadsheets/d/16IWa_TFB8wx2_R_Fk9-Y80b5n1BF32SvwwcnrsB3waA/edit#gid=0) Next I would like to follow up on Mike's suggestion and go through and removing unnecessary clutter.

**Comment by itprofjacobs** [comment]
Dooooo. Iiiiiiiit!!!!!!  :-)

**Comment by whenbellstoll** [comment]
Now that @Nolski and I have had a chance to go over the rubrics in person, we are satisfied with the state of rubrics, [look at it here.](https://docs.google.com/spreadsheets/d/16IWa_TFB8wx2_R_Fk9-Y80b5n1BF32SvwwcnrsB3waA/edit#gid=0) 
Pending reviews from @itprofjacobs  this closes the issue.

**Comment by jwflory** [comment]
@whenbellstoll @Nolski Awesome awesome work! It's so cool to see where this evolved since I last saw it. :smile: I took a quick review and had some further suggestions:

* **Quality of writing**:
    * Should be understandable for an audience whose first language is not English: Many of these groups are international and their audience for new contributors may be folks whose first language is not English. A good way to "check" this is to have others who are not native English speakers read your document(s) for understanding and clarity.
    * Also having translated versions of some content is helpful if it makes sense for your community. For example, some of the companies I remember were building products specific to communities in their country. In that case, localizing project documents to their native language would be helpful to include people from their own communities they are serving.
* **Code of Conduct**:
    * A great project should have at least two people on a Code of Conduct committee. Read [this article](https://otter.technology/blog/2019/05/23/why-train-multiple-code-of-conduct-enforcers/) for an in-depth explanation. tl;dr: conflicting roles, conflicts of interest, and bias.
    * A great project should also have a _transparent and public_ process into how responses are handled and what expectations a reporter can have when submitting a report. Naturally an organization might choose to keep this private or closed, but it's important for the reporter and community that a degree of this process is publicly documented and explained, both for accountability and assurance that a request will be taken seriously. It creates a standard.
* **README**: I think explaining the _why_ of a project is helpful to make a great README. A lot of projects focus on the technology they are using or the technical details of their project, but especially for humanitarian projects, it's an important chance to sell the mission of your project. I think it's helpful to put more emphasis on distinguishing the purpose of a project and what its perceived impact is in the README. This doesn't have to be an essay, but an elevator pitch of the important _why_ questions is useful (especially considering the social stigmas around many of the technologies used by the different UNICEF cohorts). This is like an elevator pitch of the user documentation criteria for Project Explanation.
* **Testing**: It might help to briefly distinguish between unit tests and integration tests. I think both are important and I realized when I first put together some of my criteria, I focused more on unit tests. But both are important. :smile: See a better explanation in the top-half of [this blog post](https://www.toptal.com/qa/how-to-write-testable-code-and-why-it-matters).
* **Website**: If a project is open source, they should mention their license(s) explicitly on the front-page. In the last year, we have seen a lot of turmoil around projects that claim to use open source licenses but are [not really open source](https://twitter.com/BitIntegrity/status/1124805397745766400).
* **Wiki**: A lot of this section feels duplicated from the the _User Documentation_ and _Developer Documentation_ criteria. I generally think a wiki is one of many tools a team can choose to use. It might make sense for some projects and might not from others. I think it's better to consolidate that section into the other documentation criteria to focus on being general instead of specific to a single type of tool. What do you think?

I feel like now that things are more developed, it's easier to give detailed feedback for fine-tuning. Keep up the awesome work. :raised_hands:

**Comment by whenbellstoll** [comment]
The edits suggested by @jwflory  have been made, again working document is [here.](https://docs.google.com/spreadsheets/d/16IWa_TFB8wx2_R_Fk9-Y80b5n1BF32SvwwcnrsB3waA/edit#gid=0) @Nolski  @itprofjacobs  and myself had a meeting Tuesday where we decided we also wanted to attach resources to the rubric.
