### ISSUE TITLE
UNICEF Kent Open Source Reading

### ISSUE THREAD

**Issue by whenbellstoll** [FOSSRIT/tasks#88]
# Summary

Currently unfamiliar with the book [Producing Open Source Software](https://producingoss.com/en/producingoss.pdf) and should read it as a reference for FOSS methods.

# Background

Justin built the Flory Plan off of this book, so it would be beneficial to read and understand the material.

# Details

- Read the material
- Take notes
- Have a strong comprehension of topics and methods.

# Outcome

Kent will be more informed on FOSS and its methods.

**Comment by ritjoe** [comment]
On Mon, May 13, 2019 at 04:44:43PM +0000, Kent Reese wrote:

> Currently unfamiliar with the book Producing Open Source Software and should
> read it as a reference for FOSS methods.

I found that sometimes when I get stuck on a reading, it helps me compare and contrast it with another work covering similar ground. 

In that spirit I offer the Github-affiliated Open Source Guides as a complement to Fogel's book:

https://github.blog/2017-02-14-announcing-open-source-guides/

in case it proves useful or helpful to compare and contrast 

(I mention this not in any way to say you need to read all of it in addition to Fogel, too,
or that you should read it instead of Fogel, just that it's there if you need it).

The Guides are CC-BY-4.0 and Fogel's book is CC-BY-SA-4.0.
